networks:
  bridge:
    driver: bridge
  kafka_network:
    external: true  # Connect to your existing Kafka network

services:
  postgres:
    build:
      context: ./postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5432:5432
    networks:
      - bridge
  
  option-greeks-processor:
    build:
      context: ./option-greeks-processor
    environment:
      # Connect to your existing Kafka service
      KAFKA_SERVER: "kafka:9092"         # Update this to your Kafka broker address
      KAFKA_TOPIC: "options"             # Update this to your options data topic
      POSTGRES_HOST: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    networks:
      - bridge
      - kafka_network  # Connect to existing Kafka network

volumes:
  postgres-data: